### ISSUE TITLE
Cannot log after tests are done. Did you forget to wait for something async in your test?

### ISSUE THREAD

**Issue by gran33** [wix/remx#47]
Hi, 
During my tests, I keep seeing this warning:
  ```Cannot log after tests are done. Did you forget to wait for something async in your test?
    Attempted to log "[mobx] Warning: there are multiple mobx instances active. This might lead to unexpected results. See https://github.com/mobxjs/mobx/issues/1082 for details.".

      at BufferedConsole.warn (node_modules/@jest/console/build/BufferedConsole.js:224:10)
      at Timeout._onTimeout (node_modules/mobx/lib/mobx.js:2700:25)
```

Any help how to eliminate it?
@Niryo @DanielZlotin

**Comment by sgovindan** [comment]
I am to facing this issue on Jenkins.

**Comment by andykog** [comment]
@gran33, Jest executes files multiple times if you require them inside tests, so mobx is being executed multiple times.
I've used this workaround (there might be something better):
```js
    afterEach(() => {
      delete global.__mobxInstanceCount; // prevent warnings
    })
```
Could you try it and see if it helps?
