### ISSUE TITLE
Cannot log after tests are done. Did you forget to wait for something async in your test?

### ISSUE THREAD

**Issue by gran33** [wix/remx#48]
Hi, 
During my tests, I keep seeing this warning:
  ```Cannot log after tests are done. Did you forget to wait for something async in your test?
    Attempted to log "[mobx] Warning: there are multiple mobx instances active. This might lead to unexpected results. See https://github.com/mobxjs/mobx/issues/1082 for details.".

      at BufferedConsole.warn (node_modules/@jest/console/build/BufferedConsole.js:224:10)
      at Timeout._onTimeout (node_modules/mobx/lib/mobx.js:2700:25)
```

This might be helpful:
https://github.com/mobxjs/mobx/issues/1082#issuecomment-352409804

Any help how to eliminate it?
@Niryo @DanielZlotin

**Comment by andykog** [comment]
Closing as duplicate of #47
